version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432 # Порт внутри контейнера
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    depends_on:
      - db
    networks:
      - auth-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    ports:
      - "5505:5505" # Порт 5433 на хосте, 5432 внутри контейнера
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - auth-network

networks:
  auth-network:

volumes:
  db-data:
