version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111"  # Порт для приложения
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432  # Порт базы данных внутри контейнера
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    depends_on:
      - db
    networks:
      - auth-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    ports:
      - "3333:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth-network

networks:
  auth-network:

volumes:
  db-data:
